---
- name: Create neutron database
  mysql_db:
    login_user: root
    name: neutron
    state: present

- name: Grant all privileges on neutron db to user neutron
  mysql_user:
    login_user: root
    name: neutron
    host: "{{ item }}"
    password: "{{ os_neutron_mysql_password }}"
    priv: 'neutron.*:ALL'
    state: present
  with_items:
    - "localhost"
    - "%"

- name: Create the neutron user
  os_user:
    name: neutron
    password: "{{ os_neutron_password }}"
    domain: default
    state: present

- name: Add the admin role to the neutron user and service project
  os_user_role:
    role: admin
    user: neutron
    project: service

- name: Create the neutron service entity
  os_keystone_service:
    name: neutron
    service_type: network
    description: "OpenStack Networking"
    state: present

- name: Create the Networking API endpoints
  os_keystone_endpoint:
    service: neutron
    endpoint_interface: "{{ item.endpoint_interface }}"
    url: http://controller:9696
    region: RegionOne
    state: present
  with_items:
    - { endpoint_interface: public }
    - { endpoint_interface: internal }
    - { endpoint_interface: admin }

- name: Install neutron packages
  apt:
    name: "{{ item }}"
    state: present
  with_items:
    - neutron-server
    - neutron-plugin-ml2
    - neutron-l3-agent
    - neutron-dhcp-agent
    - neutron-metadata-agent

- name: Install neutron openvswitch agent
  apt:
    name: "neutron-openvswitch-agent"
    state: present
  when: "os_neutron_driver == 'openvswitch'"

- name: Install neutron linuxbridge agent
  apt:
    name: "neutron-linuxbridge-agent"
    state: present
  when: "os_neutron_driver == 'linuxbridge'"

- name: Populate neutron config files
  ini_file:
    path: "{{ item.path }}"
    section: "{{ item.section }}"
    option: "{{ item.option }}"
    value: "{{ item.value }}"
  with_items:
    - { path: "/etc/neutron/neutron.conf", section: "database", option: "connection", value: "mysql+pymysql://neutron:{{ os_neutron_mysql_password }}@controller/neutron" }
    - { path: "/etc/neutron/neutron.conf", section: "DEFAULT", option: "core_plugin", value: "ml2" }
    - { path: "/etc/neutron/neutron.conf", section: "DEFAULT", option: "service_plugins", value: "router" }
    - { path: "/etc/neutron/neutron.conf", section: "DEFAULT", option: "allow_overlapping_ips", value: "true" }
    - { path: "/etc/neutron/neutron.conf", section: "DEFAULT", option: "transport_url", value: "rabbit://openstack:{{ os_env_rabbitmq_openstack_password }}@controller" }
    - { path: "/etc/neutron/neutron.conf", section: "DEFAULT", option: "auth_strategy", value: "keystone" }
    - { path: "/etc/neutron/neutron.conf", section: "keystone_authtoken", option: "auth_uri", value: "http://controller:5000" }
    - { path: "/etc/neutron/neutron.conf", section: "keystone_authtoken", option: "auth_url", value: "http://controller:5000" }
    - { path: "/etc/neutron/neutron.conf", section: "keystone_authtoken", option: "memcached_servers", value: "controller:11211" }
    - { path: "/etc/neutron/neutron.conf", section: "keystone_authtoken", option: "auth_type", value: "password" }
    - { path: "/etc/neutron/neutron.conf", section: "keystone_authtoken", option: "project_domain_name", value: "default" }
    - { path: "/etc/neutron/neutron.conf", section: "keystone_authtoken", option: "user_domain_name", value: "default" }
    - { path: "/etc/neutron/neutron.conf", section: "keystone_authtoken", option: "project_name", value: "service" }
    - { path: "/etc/neutron/neutron.conf", section: "keystone_authtoken", option: "username", value: "neutron" }
    - { path: "/etc/neutron/neutron.conf", section: "keystone_authtoken", option: "password", value: "{{ os_neutron_password }}" }
    - { path: "/etc/neutron/neutron.conf", section: "DEFAULT", option: "notify_nova_on_port_status_changes", value: "true" }
    - { path: "/etc/neutron/neutron.conf", section: "DEFAULT", option: "notify_nova_on_port_data_changes", value: "true" }
    - { path: "/etc/neutron/neutron.conf", section: "nova", option: "auth_url", value: "http://controller:5000" }
    - { path: "/etc/neutron/neutron.conf", section: "nova", option: "auth_type", value: "password" }
    - { path: "/etc/neutron/neutron.conf", section: "nova", option: "project_domain_name", value: "default" }
    - { path: "/etc/neutron/neutron.conf", section: "nova", option: "user_domain_name", value: "default" }
    - { path: "/etc/neutron/neutron.conf", section: "nova", option: "region_name", value: "RegionOne" }
    - { path: "/etc/neutron/neutron.conf", section: "nova", option: "project_name", value: "service" }
    - { path: "/etc/neutron/neutron.conf", section: "nova", option: "username", value: "nova" }
    - { path: "/etc/neutron/neutron.conf", section: "nova", option: "password", value: "{{ os_nova_password }}" }
    - { path: "/etc/neutron/plugins/ml2/ml2_conf.ini", section: "ml2", option: "type_drivers", value: "flat,vlan,vxlan" }
    - { path: "/etc/neutron/plugins/ml2/ml2_conf.ini", section: "ml2", option: "tenant_network_types", value: "vxlan" }
    - { path: "/etc/neutron/plugins/ml2/ml2_conf.ini", section: "ml2", option: "extension_drivers", value: "port_security" }
    - { path: "/etc/neutron/plugins/ml2/ml2_conf.ini", section: "ml2_type_flat", option: "flat_networks", value: "{{ os_neutron_provider_network_name }}" }
    - { path: "/etc/neutron/plugins/ml2/ml2_conf.ini", section: "ml2_type_vxlan", option: "vni_ranges", value: "1:1000" }
    - { path: "/etc/neutron/plugins/ml2/ml2_conf.ini", section: "securitygroup", option: "enable_ipset", value: "true" }
    - { path: "/etc/neutron/dhcp_agent.ini", section: "DEFAULT", option: "enable_isolated_metadata", value: "true" }
    - { path: "/etc/neutron/metadata_agent.ini", section: "DEFAULT", option: "nova_metadata_host", value: "controller" }
    - { path: "/etc/neutron/metadata_agent.ini", section: "DEFAULT", option: "metadata_proxy_shared_secret", value: "{{ os_neutron_metadata_secret }}" }
    - { path: "/etc/nova/nova.conf", section: "neutron", option: "url", value: "http://controller:9696" }
    - { path: "/etc/nova/nova.conf", section: "neutron", option: "auth_url", value: "http://controller:5000" }
    - { path: "/etc/nova/nova.conf", section: "neutron", option: "auth_type", value: "password" }
    - { path: "/etc/nova/nova.conf", section: "neutron", option: "project_domain_name", value: "default" }
    - { path: "/etc/nova/nova.conf", section: "neutron", option: "user_domain_name", value: "default" }
    - { path: "/etc/nova/nova.conf", section: "neutron", option: "region_name", value: "RegionOne" }
    - { path: "/etc/nova/nova.conf", section: "neutron", option: "project_name", value: "service" }
    - { path: "/etc/nova/nova.conf", section: "neutron", option: "username", value: "neutron" }
    - { path: "/etc/nova/nova.conf", section: "neutron", option: "password", value: "{{ os_neutron_password }}" }
    - { path: "/etc/nova/nova.conf", section: "neutron", option: "service_metadata_proxy", value: "true" }
    - { path: "/etc/nova/nova.conf", section: "neutron", option: "metadata_proxy_shared_secret", value: "{{ os_neutron_metadata_secret }}" }

- name: Populate neutron openvswitch agent config
  ini_file:
    path: "{{ item.path }}"
    section: "{{ item.section }}"
    option: "{{ item.option }}"
    value: "{{ item.value }}"
  with_items:
    - { path: "/etc/neutron/l3_agent.ini", section: "DEFAULT", option: "interface_driver", value: "openvswitch" }
    - { path: "/etc/neutron/l3_agent.ini", section: "DEFAULT", option: "external_network_bridge", value: "" }
    - { path: "/etc/neutron/dhcp_agent.ini", section: "DEFAULT", option: "interface_driver", value: "openvswitch" }
    - { path: "/etc/neutron/dhcp_agent.ini", section: "DEFAULT", option: "force_metadata", value: "true" }
    - { path: "/etc/neutron/plugins/ml2/ml2_conf.ini", section: "ml2", option: "mechanism_drivers", value: "openvswitch,l2population" }
    - { path: "/etc/neutron/plugins/ml2/openvswitch_agent.ini", section: "ovs", option: "bridge_mappings", value: "{{ os_neutron_provider_network_name }}:{{ os_neutron_provider_interface_name }}" }
    - { path: "/etc/neutron/plugins/ml2/openvswitch_agent.ini", section: "ovs", option: "local_ip", value: "{{ os_management_ip }}" }
    - { path: "/etc/neutron/plugins/ml2/openvswitch_agent.ini", section: "agent", option: "tunnel_types", value: "vxlan" }
    - { path: "/etc/neutron/plugins/ml2/openvswitch_agent.ini", section: "agent", option: "l2_population", value: "true" }
    - { path: "/etc/neutron/plugins/ml2/openvswitch_agent.ini", section: "securitygroup", option: "firewall_driver", value: "iptables_hybrid" }
  when: "os_neutron_driver == 'openvswitch'"

- name: Populate neutron linuxbridge agent config
  ini_file:
    path: "{{ item.path }}"
    section: "{{ item.section }}"
    option: "{{ item.option }}"
    value: "{{ item.value }}"
  with_items:
    - { path: "/etc/neutron/l3_agent.ini", section: "DEFAULT", option: "interface_driver", value: "linuxbridge" }
    - { path: "/etc/neutron/dhcp_agent.ini", section: "DEFAULT", option: "interface_driver", value: "linuxbridge" }
    - { path: "/etc/neutron/dhcp_agent.ini", section: "DEFAULT", option: "dhcp_driver", value: "neutron.agent.linux.dhcp.Dnsmasq" }
    - { path: "/etc/neutron/plugins/ml2/ml2_conf.ini", section: "ml2", option: "mechanism_drivers", value: "linuxbridge,l2population" }
    - { path: "/etc/neutron/plugins/ml2/linuxbridge_agent.ini", section: "linux_bridge", option: "physical_interface_mappings", value: "{{ os_neutron_provider_network_name }}:{{ os_neutron_provider_interface_name }}" }
    - { path: "/etc/neutron/plugins/ml2/linuxbridge_agent.ini", section: "vxlan", option: "enable_vxlan", value: "true" }
    - { path: "/etc/neutron/plugins/ml2/linuxbridge_agent.ini", section: "vxlan", option: "local_ip", value: "{{ os_management_ip }}" }
    - { path: "/etc/neutron/plugins/ml2/linuxbridge_agent.ini", section: "vxlan", option: "l2_population", value: "true" }
    - { path: "/etc/neutron/plugins/ml2/linuxbridge_agent.ini", section: "securitygroup", option: "enable_security_group", value: "true" }
    - { path: "/etc/neutron/plugins/ml2/linuxbridge_agent.ini", section: "securitygroup", option: "firewall_driver", value: "neutron.agent.linux.iptables_firewall.IptablesFirewallDriver" }
  when: "os_neutron_driver == 'linuxbridge'"

- name: Ensure kernel supports network bridge filters
  sysctl:
    name: "{{ item }}"
    value: 1
    state: present
  with_items:
    - "net.bridge.bridge-nf-call-iptables"
    - "net.bridge.bridge-nf-call-ip6tables"
  when: "os_neutron_driver == 'linuxbridge'"

- name: Populate the neutron database
  become: true
  become_user: neutron
  vars:
    ansible_ssh_pipelining: true
  shell: "neutron-db-manage --config-file /etc/neutron/neutron.conf --config-file /etc/neutron/plugins/ml2/ml2_conf.ini upgrade head"

- name: Restart the Compute API service
  service:
    name: nova-api
    state: restarted

- name: Restart the Networking services
  service:
    name: "{{ item }}"
    state: restarted
  with_items:
    - neutron-server
    - neutron-dhcp-agent
    - neutron-metadata-agent
    - neutron-l3-agent

- name: Restart the openvswitch agent
  service:
    name: "neutron-openvswitch-agent"
    state: restarted
  when: "os_neutron_driver == 'openvswitch'"


- name: Restart the linuxbridge agent
  service:
    name: "neutron-linuxbridge-agent"
    state: restarted
  when: "os_neutron_driver == 'linuxbridge'"
