---
  - hosts: openstack
    gather_facts: no
    roles:
      - { role: os-flavor }
      - { role: os-security-group }
      - { role: os-image }
      - { role: os-keypair }
      - { role: os-server }
